### ISSUE TITLE
App crashes if directory name contains Chinese characters

### ISSUE THREAD

**Issue by jonolumb** [GijsGoudzwaard/Image-Optimizer#24]
When I drag photos from a folder whose name contains Chinese characters (for example 测试, Chinese for test), Image Optimizer crashes. If I rename the folder to only contain alphanumeric characters (for example, test), everything works fine. Would appreciate it if this issue could be fixed. Thanks!

**Comment by rusty-snake** [comment]
Identical with special german characters (`äöüÄÖÜ`).

**Comment by VentGrey** [comment]
That's because those chats are unicode and might not work correctly with
the actual name parsing of the application

 https://wiki.gnome.org/Projects/Vala/StringSample

**Comment by Hackgets** [comment]
I also drop files with paths containing katakana which causes the app to crash.

- Zorin OS 16.1 Based on Ubuntu 20.04.3 LTS

**Comment by ryonakano** [comment]
Leaving the backtrace when running `G_DEBUG=fatal-criticals gdb com.github.gijsgoudzwaard.image-optimizer`:

```
(com.github.gijsgoudzwaard.image-optimizer:25264): GLib-CRITICAL **: 23:51:15.569: g_strsplit: assertion 'string != NULL' failed

Thread 7 "thread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fffd6a006c0 (LWP 25272)]
0x00007ffff7e5f6a1 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7e5f6a1 in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7e5f953 in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7e7ede5 in g_strsplit () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x0000555555566341 in opti_png_getNewSize (self=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.

   , stdout=0x7fffd0001450 "** Processing: /home/ryo/Pictures/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3.png\nError: Can't open the input file\n\n** Status report\n1 file(s) have been processed.\n1 error(s) have been encountered.\n") at ../src/Utils/OptiPng.vala:93
#4  0x0000555555565dc3 in __lambda7_ (_data2_=0x555555b04d40) at ../src/Utils/OptiPng.vala:67
#5  0x0000555555565ff4 in ___lambda7__gthread_func (self=0x555555b04d40) at /home/ryo/work/tmp/Image-Optimizer/builddir/OptiPng.c:623
#6  0x00007ffff7e88c82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff709ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#8  0x00007ffff7129c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb)
```

**Comment by ryonakano** [comment]
Leaving the backtrace when running gdb:

```
(com.github.gijsgoudzwaard.image-optimizer:25588): GLib-CRITICAL **: 23:55:03.154: g_strsplit: assertion 'string != NULL' failed

Thread 7 "thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6a006c0 (LWP 25597)]
0x0000555555566368 in opti_png_getNewSize (self=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
,
    stdout=0x7fffd0001450 "** Processing: /home/ryo/Pictures/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3.png\nError: Can't open the input file\n\n** Status report\n1 file(s) have been processed.\n1 error(s) have been encountered.\n") at ../src/Utils/OptiPng.vala:93
93          return int.parse(text.split(" ")[0]);
(gdb) bt
#0  0x0000555555566368 in opti_png_getNewSize (self=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.

   , stdout=0x7fffd0001450 "** Processing: /home/ryo/Pictures/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3.png\nError: Can't open the input file\n\n** Status report\n1 file(s) have been processed.\n1 error(s) have been encountered.\n") at ../src/Utils/OptiPng.vala:93
#1  0x0000555555565dc3 in __lambda7_ (_data2_=0x555555b06160) at ../src/Utils/OptiPng.vala:67
#2  0x0000555555565ff4 in ___lambda7__gthread_func (self=0x555555b06160) at /home/ryo/work/tmp/Image-Optimizer/builddir/OptiPng.c:623
#3  0x00007ffff7e88c82 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff709ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#5  0x00007ffff7129c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb)
```
